name: Issue Labeler

on:
  issues:
    types:
      - opened
      - edited

permissions:
  issues: write
  contents: read

jobs:
  label-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract issue details and label
        id: extract-labels
        uses: actions/github-script@v6
        with:
          script: |
            const issue = context.issue;
            const issueBody = context.payload.issue.body;

            // Function to extract specific fields from the issue body
            function extractField(field) {
              const regex = new RegExp(`### ${field}\\n\\n(.*)\\n`, 'i');
              const match = issueBody.match(regex);
              return match ? match[1].trim() : null;
            }

            const targetMilestone = extractField('Target Milestone');
            const epic = extractField('Epic');
            const labels = [];

            if (targetMilestone) {
              labels.push(`milestone-${targetMilestone.toLowerCase().replace(/\s+/g, '-')}`);
            }

            if (epic) {
              labels.push(`epic-${epic.toLowerCase().replace(/\s+/g, '-')}`);
            }

            // Set output
            core.setOutput("labels", labels.join(','));

      - run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS:  ${{ steps.extract-labels.outputs.labels }}