name: Issue Labeler

on:
  issues:
    types:
      - opened
      - edited

permissions:
  issues: write
  contents: read

jobs:
  label-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract issue details and label
        id: extract-labels
        run: |
          echo "Extracting labels from issue"
          labels=$(jq -r '.issue.body' "$GITHUB_EVENT_PATH" | awk '/### Target Milestone/{getline; print}' | sed 's/^ *//;s/ *$//')
          epic=$(jq -r '.issue.body' "$GITHUB_EVENT_PATH" | awk '/### Epic/{getline; print}' | sed 's/^ *//;s/ *$//')
          labels_array=""
          if [ -n "$labels" ]; then
            labels_array="milestone-${labels,,}"
          fi
          if [ -n "$epic" ]; then
            if [ -n "$labels_array" ]; then
              labels_array="$labels_array,epic-${epic,,}"
            else
              labels_array="epic-${epic,,}"
            fi
          fi
          echo "labels=$labels_array" >> $GITHUB_ENV

      - name: Add labels
        run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS:  ${{ env.labels }}